### ISSUE TITLE
About Select the Best Model (evolution_search.py)

### ISSUE THREAD

**Issue by Zhaoyu321** [mit-han-lab/gan-compression#103]
Sorry for the interruption！I successfully completed the training of the supernet on my own dataset. When I proceeded to the next stage (e.g run evolution_search.py), I find that when I changed the input size to 272x880，the code cannot continue to run, like this:
-----------------------------------------------
Start Evolution...
Sample     :   0%|                                      | 0/100 [00:00<?, ?it/s]
however, when I changed the input size to 256x256 (same size as paper)，the code can works fine. Note that, I use the size of 272X880 successfully completed the first stage training and supernet training, just  run evolution_search.py that the problem arose. I tried changing some parameter settings and codes, but it didn't work.
May I ask if it is only limited to a fixed input size of 256 or there are other reasons？
Sincere Regards！

**Comment by lmxyy** [comment]
Hi! I suppose this is just because your model needs more MACs when the resolution is higher. In this case, the previous budget constraint may be infeasible for this resolution. What you could do is try to increase the budget to see if it could work or not with [`--budget $MACS`](https://github.com/mit-han-lab/gan-compression/blob/b23f7eb1541f66a39f3fabb017293afd976e1038/options/evolution_options.py#L34).

**Comment by Zhaoyu321** [comment]
> Hi! I suppose this is just because your model needs more MACs when the resolution is higher. In this case, the previous budget constraint may be infeasible for this resolution. What you could do is try to increase the budget to see if it could work or not with [`--budget $MACS`](https://github.com/mit-han-lab/gan-compression/blob/b23f7eb1541f66a39f3fabb017293afd976e1038/options/evolution_options.py#L34).

Thank you very much!  It is just the budget that causes the problem. I increase the budget and the code can continue run.
