### ISSUE TITLE
SERACH MULTI

### ISSUE THREAD

**Issue by EliteBeastSlamor** [mit-han-lab/gan-compression#29]
I had successfully run search.py and evaluate sub-models, but when using search_multi.py, there is an error says 
'RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 6 does not equal 0', which means Tensor or model is not on the same GPU. 

How can I run search_multi.py successfully?

**Comment by lmxyy** [comment]
Sorry. Could you please tell me which model are you compressing?

**Comment by lmxyy** [comment]
Sorry, could you please tell me which model are you compressing?

Since `search_multi.py` sometimes may cause a deadlock, I didn't update it for some time. So I do not recommend you use it. 
If you need parallel multi-GPU searching, you could manually split the search space with `search.py`. All you need to do is add additional arguments `--split` and `--remainder`. For example, if you need to search the sub-networks for cycleGAN with 2 GPUs, you could use the following commands:
```bash
python search.py --dataroot database/horse2zebra/valA \
  --dataset_mode single \
  --restore_G_path logs/cycle_gan/horse2zebra/supernet/checkpoints/latest_net_G.pth \
  --output_path logs/cycle_gan/horse2zebra/supernet/pkls/result0.pkl \
  --ngf 32 --batch_size 32 \
  --config_set channels-32 \
  --real_stat_path real_stat/horse2zebra_B.npz \
  --split 2 --remainder 0
```
And on the second GPU
```bash
python search.py --dataroot database/horse2zebra/valA \
  --dataset_mode single \
  --restore_G_path logs/cycle_gan/horse2zebra/supernet/checkpoints/latest_net_G.pth \
  --output_path logs/cycle_gan/horse2zebra/supernet/pkls/result1.pkl \
  --ngf 32 --batch_size 32 \
  --config_set channels-32 \
  --real_stat_path real_stat/horse2zebra_B.npz \
  --split 2 --remainder 1 --gpu_ids 1
```
And then you could merge the search results with `merge.py`:
```bash
python merge.py --in_dir logs/cycle_gan/horse2zebra/supernet/pkls --output_path logs/cycle_gan/horse2zebra/supernet
```

I will try to fix the `search_multi.py`.

**Comment by EliteBeastSlamor** [comment]
Good solving method, I'll try it! Thanks for the answer!
