### ISSUE TITLE
using the compressed model on a Raspberry Pi 4

### ISSUE THREAD

**Issue by seekingdeep** [mit-han-lab/gan-compression#50]
@lmxyy @junyanz 
Hi there,

after exporting the final CycleGAN model, how can i use it on a Raspberry Pi 4?

**Comment by MuyangLi-Dawnlight** [comment]
We have not used our models on Raspberry Pi 4, so we do not know the detailed process to run it.
But I think the process is almost equal to run a normal PyTorch model on Raspberry Pi 4. You will need to install PyTorch on Raspberry Pi 4, and since it does not have GPU, you should disable the GPU usage with the option `--gpu_ids -1`.

**Comment by lmxyy** [comment]
We have not used our models on Raspberry Pi 4, so we do not know the detailed process to run it.
But I think the process is almost equal to run a normal PyTorch model on Raspberry Pi 4. You will need to install PyTorch on Raspberry Pi 4, and since it does not have GPU, you should disable the GPU usage with the option `--gpu_ids -1`.

**Comment by seekingdeep** [comment]
alright, i should test that, thanks
