### ISSUE TITLE
Training compressed model in the first place

### ISSUE THREAD

**Issue by s1ddok** [mit-han-lab/gan-compression#7]
Is it necessary to first train regular pix2pix and then compress it with the code in this repository? Is it possible to train compressed model straight away?

**Comment by lmxyy** [comment]
In order to compress the GAN generator with our repo, you need a pre-trained big model. We have released the pre-trained models at `https://hanlab.mit.edu/files/gan_compression/pretrained`. You could directly download the pre-trained models and compress the models with them. A more detailed tutorial will be released later.
